name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2
      with:
         repository: ' '
          
    - name: Build & push Docker image
      uses: jpdocker12/node-sampl@latest
      with: 
         image: jpdocker12/node-sampl
         tag: latest
         registry: docker.io
         username: $ {{ secrets.DOCK_USERNAME }}
         password: $ {{ secrets.DOCK_PWD }}
    
