name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2
      with:
         fetch-depth: 2
    - run: git checkout HEAD^ 
    
    - name: Docker login
      uses: docker/login-action@v1.6.0
      with: 
        username: ${{ secrets.DOCK_USERNAME }}
        password: ${{ secrets.DOCK_PWD }}
        
     
    - name: Build and push
      run: |
       docker build -t jpdocker12/nodejstrial@latest .
      
        
    
        
    
