name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2
      with:
         fetch-depth: 2
    - run: git checkout HEAD^       
        
    
