name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - name: check out code
    
      uses: jpdocker12/node-sampl@latest
    - name: Build & push Docker image
      with: 
         image: jpdocker12/node-sampl
         tag: latest
         registry: docker.io
         username: $ {{ secrets.DOCK_USERNAME }}
         password: $ {{ secrets.DOCK_PWD }}
    
